# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-06 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='distance_achivement_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='drone',
            name='manufacturing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='race_count',
            field=models.IntegerField(default=0),
        ),
    ]
